const popularModalCardMassive = [

{description: 'ЭТО разгоняет скуку и по-немногу входит в привычку. Тебе так хорошо, что потом ты начинаешь делать это по понедельникам, по вторникам, по средам... И всё, друже! Ты завяз... Влип... Подсел... Каждый новый клиент уверен, что с ним этого не произойдёт.... Но так хочется ещё..', 
title: 'Orgasmический',
img: 'https://lipinskieraki.com/uploads/receipts/2dac2e07247485bf5bf9daf249ecdb68.jpg',
id: 'popular-1',
Mprice: 1300,
Lprice: 1500,
XLprice: 1800
},
{description: 'Cамый топовый рецепт. А все потому что...BOOM! И ты подсел! Состав: Свежие помидоры чери, перец чили,томатный сок и сочетание трав трёх стран : Мексика, Эфиопия, Тайланд. Скажу просто, это взрыв ваших вкусовых рецепторов!',
title: 'TOMATO BOOM',
img: 'https://lipinskieraki.com/uploads/receipts/e8e3836b0d6eb6696c6277ce6f7d42f0.jpeg',
id: 'popular-2',
Mprice: 1100,
Lprice: 1200,
XLprice: 1600},

{description: 'Раки выкладываются на блюдо, а окроп/бульон разливается по кружкам или глубоким тарелкам. Употреблять рекомендую с холодной водкой. В таком варианте можно выпить ящик водки, запивая насыщенным бульоном и закусывая раками',
title: 'Козацькі під горілочку',
img: 'https://lipinskieraki.com/uploads/receipts/ebce1bd119bc1f1efed78c525d78a852.jpeg',
id: 'popular-3',
Mprice: 1400,
Lprice: 1900,
XLprice: 2000},

{description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'popular-4',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'popular-5'},
{description: 'Cамый топовый рецепт. А все потому что...BOOM! И ты подсел! Состав: Свежие помидоры чери, перец чили,томатный сок и сочетание трав трёх стран : Мексика, Эфиопия, Тайланд. Скажу просто, это взрыв ваших вкусовых рецепторов!',
title: 'TOMATO BOOM',
img: 'https://lipinskieraki.com/uploads/receipts/e8e3836b0d6eb6696c6277ce6f7d42f0.jpeg',
id: 'popular-6',
Mprice: 1100,
Lprice: 1200,
XLprice: 1600},

{description: 'Раки выкладываются на блюдо, а окроп/бульон разливается по кружкам или глубоким тарелкам. Употреблять рекомендую с холодной водкой. В таком варианте можно выпить ящик водки, запивая насыщенным бульоном и закусывая раками',
title: 'Козацькі під горілочку',
img: 'https://lipinskieraki.com/uploads/receipts/ebce1bd119bc1f1efed78c525d78a852.jpeg',
id: 'popular-7',
Mprice: 1400,
Lprice: 1900,
XLprice: 2000},

{description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'popular-8',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'popular-9',
Mprice: 1500,
Lprice: 1900,
XLprice: 2300}
];


const boiledModalCardMassive = [
    {description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
    title: 'Мюнхенский (Вареные)',
    img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
    id: 'popular-1',
    Mprice: 1000,
    Lprice: 1100,
    XLprice: 1300},
    {description: 'ЭТО разгоняет скуку и по-немногу входит в привычку. Тебе так хорошо, что потом ты начинаешь делать это по понедельникам, по вторникам, по средам... И всё, друже! Ты завяз... Влип... Подсел... Каждый новый клиент уверен, что с ним этого не произойдёт.... Но так хочется ещё..', 
title: 'Orgasmический',
img: 'https://lipinskieraki.com/uploads/receipts/bfce407e9b613dcc4b414a686ad986e8.jpg',
id: 'popular-2',
Mprice: 1300,
Lprice: 1500,
XLprice: 1800},

{description: 'Cамый топовый рецепт. А все потому что...BOOM! И ты подсел! Состав: Свежие помидоры чери, перец чили,томатный сок и сочетание трав трёх стран : Мексика, Эфиопия, Тайланд. Скажу просто, это взрыв ваших вкусовых рецепторов!',
title: 'TOMATO BOOM',
img: 'https://lipinskieraki.com/uploads/receipts/e8e3836b0d6eb6696c6277ce6f7d42f0.jpeg',
id: 'popular-3',
Mprice: 1100,
Lprice: 1200,
XLprice: 1600},

{description: 'Раки выкладываются на блюдо, а окроп/бульон разливается по кружкам или глубоким тарелкам. Употреблять рекомендую с холодной водкой. В таком варианте можно выпить ящик водки, запивая насыщенным бульоном и закусывая раками',
title: 'Козацькі під горілочку',
img: 'https://lipinskieraki.com/uploads/receipts/ebce1bd119bc1f1efed78c525d78a852.jpeg',
id: 'popular-4',
Mprice: 1400,
Lprice: 1900,
XLprice: 2000},

{description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'popular-5',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'popular-6',
Mprice: 1500,
Lprice: 1900,
XLprice: 2300},
{description: 'Раки выкладываются на блюдо, а окроп/бульон разливается по кружкам или глубоким тарелкам. Употреблять рекомендую с холодной водкой. В таком варианте можно выпить ящик водки, запивая насыщенным бульоном и закусывая раками',
title: 'Козацькі під горілочку',
img: 'https://lipinskieraki.com/uploads/receipts/ebce1bd119bc1f1efed78c525d78a852.jpeg',
id: 'popular-7',
Mprice: 1400,
Lprice: 1900,
XLprice: 2000},

{description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'popular-8',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'popular-9',
Mprice: 1500,
Lprice: 1900,
XLprice: 2300}
];

const friedModalCardMassive = [
    {description: 'Раки выкладываются на блюдо, а окроп/бульон разливается по кружкам или глубоким тарелкам. Употреблять рекомендую с холодной водкой. В таком варианте можно выпить ящик водки, запивая насыщенным бульоном и закусывая раками',
title: 'Козацькі під горілочку',
img: 'https://lipinskieraki.com/uploads/receipts/ebce1bd119bc1f1efed78c525d78a852.jpeg',
id: 'fried-1',
Mprice: 1400,
Lprice: 1900,
XLprice: 2000},
    {description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'fried-2',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},
    {description: 'ЭТО разгоняет скуку и по-немногу входит в привычку. Тебе так хорошо, что потом ты начинаешь делать это по понедельникам, по вторникам, по средам... И всё, друже! Ты завяз... Влип... Подсел... Каждый новый клиент уверен, что с ним этого не произойдёт.... Но так хочется ещё..', 
title: 'Orgasmический',
img: 'https://lipinskieraki.com/uploads/receipts/bfce407e9b613dcc4b414a686ad986e8.jpg',
id: 'fried-3',
Mprice: 1300,
Lprice: 1500,
XLprice: 1800},

{description: 'Cамый топовый рецепт. А все потому что...BOOM! И ты подсел! Состав: Свежие помидоры чери, перец чили,томатный сок и сочетание трав трёх стран : Мексика, Эфиопия, Тайланд. Скажу просто, это взрыв ваших вкусовых рецепторов!',
title: 'TOMATO BOOM',
img: 'https://lipinskieraki.com/uploads/receipts/e8e3836b0d6eb6696c6277ce6f7d42f0.jpeg',
id: 'fried-4',
Mprice: 1100,
Lprice: 1200,
XLprice: 1600},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'fried-5',
Mprice: 1500,
Lprice: 1900,
XLprice: 2300}, 
{description: 'Гурманы, живите сейчас, любите сейчас, похмеляйтесь и наслаждайтесь сегодняшним моментом. Каждая секунда - это шанс, который мы имеем, чтобы двигаться вперед. Не упустите его!',
title: 'Мюнхенский (Вареные)',
img: 'https://lipinskieraki.com/uploads/receipts/81a5e6e8df6108102d18a74d9c860c8d.jpg',
id: 'fried-6',
Mprice: 1000,
Lprice: 1100,
XLprice: 1300},
    {description: 'ЭТО разгоняет скуку и по-немногу входит в привычку. Тебе так хорошо, что потом ты начинаешь делать это по понедельникам, по вторникам, по средам... И всё, друже! Ты завяз... Влип... Подсел... Каждый новый клиент уверен, что с ним этого не произойдёт.... Но так хочется ещё..', 
title: 'Orgasmический',
img: 'https://lipinskieraki.com/uploads/receipts/bfce407e9b613dcc4b414a686ad986e8.jpg',
id: 'fried-7',
Mprice: 1300,
Lprice: 1500,
XLprice: 1800},

{description: 'Cамый топовый рецепт. А все потому что...BOOM! И ты подсел! Состав: Свежие помидоры чери, перец чили,томатный сок и сочетание трав трёх стран : Мексика, Эфиопия, Тайланд. Скажу просто, это взрыв ваших вкусовых рецепторов!',
title: 'TOMATO BOOM',
img: 'https://lipinskieraki.com/uploads/receipts/e8e3836b0d6eb6696c6277ce6f7d42f0.jpeg',
id: 'fried-8',
Mprice: 1100,
Lprice: 1200,
XLprice: 1600},

{description: '«Не откладывайте на завтра то, что можно съесть сегодня!»  Успей заказать сегодня!',
title: 'Итальянский в белом сухом вине',
img: 'https://lipinskieraki.com/uploads/receipts/a031aefb08337a5f9c0df8b59435ff3c.jpeg',
id: 'fried-9',
Mprice: 1500,
Lprice: 1900,
XLprice: 2300}
];

const mainTitleMassive = [
    {title: 'Популярные товары',
     id: 'title-1'},
     {title: 'Вареные раки',
     id: 'title-2'},
     {title: 'Жареные раки',
     id: 'title-3'}
];

export {popularModalCardMassive, boiledModalCardMassive,friedModalCardMassive, mainTitleMassive};